[package]
name = "bevy-isdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_internal = "0.8.1"
bevy_prototype_lyon = "0.6.0"
spirv_headers = ">= 1.5.0, < 1.5.1"